import { ThemePreset, UISectionColor, SyntaxScopeItem } from './types';

export const UI_COLOR_DEFINITIONS: UISectionColor[] = [
  // 1. Core Window & Editor
  { id: 'editor.background', name: 'Editor Background', description: 'Main coding canvas background color', category: 'core', defaultValue: '#1e1e1e' },
  { id: 'editor.foreground', name: 'Editor Foreground', description: 'Default text / punctuation color', category: 'core', defaultValue: '#d4d4d4' },
  { id: 'editorLineNumber.foreground', name: 'Line Numbers', description: 'Gutter line number color', category: 'core', defaultValue: '#858585' },
  { id: 'editorLineNumber.activeForeground', name: 'Active Line Number', description: 'Line number of current cursor line', category: 'core', defaultValue: '#c6c6c6' },
  { id: 'editorCursor.foreground', name: 'Editor Cursor', description: 'Blinking text cursor color', category: 'core', defaultValue: '#aeafad' },
  { id: 'editor.selectionBackground', name: 'Selection Background', description: 'Highlighted text selection area', category: 'core', defaultValue: '#264f78' },
  { id: 'editor.lineHighlightBackground', name: 'Line Highlight', description: 'Background of line cursor is currently on', category: 'core', defaultValue: '#2a2d2e' },
  { id: 'focusBorder', name: 'Focus Border', description: 'Global focus outline on interactive elements', category: 'core', defaultValue: '#007fd4' },

  // 2. Navigation & Activity Bars
  { id: 'activityBar.background', name: 'Activity Bar Background', description: 'Leftmost primary icon strip', category: 'bars', defaultValue: '#333333' },
  { id: 'activityBar.foreground', name: 'Activity Bar Icons', description: 'Active activity bar icon color', category: 'bars', defaultValue: '#ffffff' },
  { id: 'activityBar.inactiveForeground', name: 'Inactive Activity Icons', description: 'Inactive activity bar icon color', category: 'bars', defaultValue: '#858585' },
  { id: 'activityBarBadge.background', name: 'Activity Bar Badge BG', description: 'Notification badge background (e.g. Git count)', category: 'bars', defaultValue: '#007acc' },
  { id: 'activityBarBadge.foreground', name: 'Activity Bar Badge Text', description: 'Notification badge text color', category: 'bars', defaultValue: '#ffffff' },
  { id: 'sideBar.background', name: 'Sidebar Background', description: 'Explorer / Search / Extensions side panel', category: 'bars', defaultValue: '#252526' },
  { id: 'sideBar.foreground', name: 'Sidebar Foreground', description: 'File tree and side panel text color', category: 'bars', defaultValue: '#cccccc' },
  { id: 'sideBarTitle.foreground', name: 'Sidebar Title', description: 'Sidebar section header text color', category: 'bars', defaultValue: '#bbbbbb' },
  { id: 'sideBarSectionHeader.background', name: 'Sidebar Section Header BG', description: 'Background of accordion section titles', category: 'bars', defaultValue: '#333333' },
  { id: 'titleBar.activeBackground', name: 'Title Bar Background', description: 'Top window title bar background', category: 'bars', defaultValue: '#3c3c3c' },
  { id: 'titleBar.activeForeground', name: 'Title Bar Foreground', description: 'Top window title bar text color', category: 'bars', defaultValue: '#cccccc' },
  { id: 'statusBar.background', name: 'Status Bar Background', description: 'Bottom status bar normal background', category: 'bars', defaultValue: '#007acc' },
  { id: 'statusBar.foreground', name: 'Status Bar Foreground', description: 'Bottom status bar text & icon color', category: 'bars', defaultValue: '#ffffff' },
  { id: 'statusBar.debuggingBackground', name: 'Status Bar Debugging BG', description: 'Status bar background during debugging session', category: 'bars', defaultValue: '#cc6633' },

  // 3. Editor Tabs & Breadcrumbs
  { id: 'editorGroupHeader.tabsBackground', name: 'Tabs Bar Background', description: 'Background of the entire tab header bar', category: 'tabs', defaultValue: '#252526' },
  { id: 'tab.activeBackground', name: 'Active Tab Background', description: 'Background of currently open file tab', category: 'tabs', defaultValue: '#1e1e1e' },
  { id: 'tab.activeForeground', name: 'Active Tab Text', description: 'Text color of currently open file tab', category: 'tabs', defaultValue: '#ffffff' },
  { id: 'tab.activeBorderTop', name: 'Active Tab Top Border', description: 'Top accent indicator on active tab', category: 'tabs', defaultValue: '#007acc' },
  { id: 'tab.inactiveBackground', name: 'Inactive Tab Background', description: 'Background of inactive file tabs', category: 'tabs', defaultValue: '#2d2d2d' },
  { id: 'tab.inactiveForeground', name: 'Inactive Tab Text', description: 'Text color of inactive file tabs', category: 'tabs', defaultValue: '#858585' },
  { id: 'tab.hoverBackground', name: 'Tab Hover Background', description: 'Background when hovering over a tab', category: 'tabs', defaultValue: '#333333' },
  { id: 'breadcrumb.foreground', name: 'Breadcrumbs Text', description: 'File path breadcrumbs navigation text', category: 'tabs', defaultValue: '#a0a0a0' },

  // 4. Terminal & Panels
  { id: 'terminal.background', name: 'Terminal Background', description: 'Integrated terminal console background', category: 'terminal', defaultValue: '#1e1e1e' },
  { id: 'terminal.foreground', name: 'Terminal Foreground', description: 'Integrated terminal normal text color', category: 'terminal', defaultValue: '#cccccc' },
  { id: 'terminalCursor.foreground', name: 'Terminal Cursor', description: 'Integrated terminal cursor color', category: 'terminal', defaultValue: '#007acc' },
  { id: 'terminal.ansiGreen', name: 'Terminal ANSI Green', description: 'Terminal green color (success / output)', category: 'terminal', defaultValue: '#4ec9b0' },
  { id: 'terminal.ansiCyan', name: 'Terminal ANSI Cyan', description: 'Terminal cyan color (info / URLs)', category: 'terminal', defaultValue: '#9cdcfe' },
  { id: 'terminal.ansiYellow', name: 'Terminal ANSI Yellow', description: 'Terminal yellow color (warnings)', category: 'terminal', defaultValue: '#dcdcaa' },

  // 5. Chat & AI Widgets
  { id: 'interactive.requestBackground', name: 'Chat Prompt Box BG', description: 'Background for chat user input box', category: 'chat', defaultValue: '#252526' },
  { id: 'textCodeBlock.background', name: 'Chat Code Block BG', description: 'Background of formatted code blocks in chat', category: 'chat', defaultValue: '#1a1a1a' },
  { id: 'textLink.foreground', name: 'Chat Hyperlinks', description: 'Color of clickable markdown links', category: 'chat', defaultValue: '#3794ff' },
  { id: 'badge.background', name: 'General Badge BG', description: 'Pills and tag badges in chat and lists', category: 'chat', defaultValue: '#4d4d4d' },
  { id: 'badge.foreground', name: 'General Badge Text', description: 'Text inside pills and tag badges', category: 'chat', defaultValue: '#ffffff' },
];

export const SYNTAX_SCOPE_DEFINITIONS: SyntaxScopeItem[] = [
  { id: 'keywords', name: 'Keywords & Control Flow', description: 'if, else, return, const, let, class, import, async, export', scopes: ['keyword', 'keyword.control', 'storage.type', 'storage.modifier'], defaultColor: '#569cd6' },
  { id: 'functions', name: 'Functions & Methods', description: 'function names, method calls, constructors', scopes: ['entity.name.function', 'support.function', 'meta.function-call'], defaultColor: '#dcdcaa' },
  { id: 'strings', name: 'Strings & Templates', description: 'quoted text, template literals, character literals', scopes: ['string', 'string.quoted', 'string.template'], defaultColor: '#ce9178' },
  { id: 'variables', name: 'Variables & Identifiers', description: 'variable names, parameters, object properties', scopes: ['variable', 'variable.other', 'variable.parameter'], defaultColor: '#9cdcfe' },
  { id: 'types', name: 'Types & Classes', description: 'interfaces, type aliases, classes, struct names', scopes: ['entity.name.type', 'support.type', 'entity.name.class'], defaultColor: '#4ec9b0' },
  { id: 'comments', name: 'Comments', description: 'single-line // and multi-line /* */ comments', scopes: ['comment', 'comment.line', 'comment.block'], defaultColor: '#6a9955' },
  { id: 'numbers', name: 'Numbers & Booleans', description: 'integers, floats, true, false, null, undefined', scopes: ['constant.numeric', 'constant.language.boolean', 'constant.language'], defaultColor: '#b5cea8' },
  { id: 'operators', name: 'Operators & Punctuation', description: '+, -, *, =, =>, ==, &&, ||, ;, :, ,', scopes: ['keyword.operator', 'punctuation.separator', 'punctuation.terminator'], defaultColor: '#d4d4d4' },
  { id: 'tags', name: 'HTML / JSX Tags & Attributes', description: 'div, span, Button, onClick, className', scopes: ['entity.name.tag', 'entity.other.attribute-name'], defaultColor: '#4fc1ff' },
];

export const THEME_PRESETS: ThemePreset[] = [
  // 1. Cyberpunk Neon
  {
    id: 'cyberpunk-neon',
    name: '⚡ Cyberpunk Neon',
    description: 'High-contrast OLED deep black with electric neon yellow, cyan, and hot pink accents.',
    type: 'dark',
    accentColor: '#ffe600',
    colors: {
      'editor.background': '#07070a',
      'editor.foreground': '#f0f0f8',
      'editorLineNumber.foreground': '#454558',
      'editorLineNumber.activeForeground': '#ffe600',
      'editorCursor.foreground': '#ffe600',
      'editor.selectionBackground': '#2a0845cc',
      'editor.lineHighlightBackground': '#14141ecc',
      'focusBorder': '#ffe600',
      'activityBar.background': '#050508',
      'activityBar.foreground': '#ffe600',
      'activityBar.inactiveForeground': '#555566',
      'activityBarBadge.background': '#ff0055',
      'activityBarBadge.foreground': '#ffffff',
      'sideBar.background': '#09090e',
      'sideBar.foreground': '#d0d0e0',
      'sideBarTitle.foreground': '#ffe600',
      'sideBarSectionHeader.background': '#111118',
      'titleBar.activeBackground': '#050508',
      'titleBar.activeForeground': '#ffe600',
      'statusBar.background': '#050508',
      'statusBar.foreground': '#ffe600',
      'statusBar.debuggingBackground': '#ff0055',
      'editorGroupHeader.tabsBackground': '#09090e',
      'tab.activeBackground': '#07070a',
      'tab.activeForeground': '#ffe600',
      'tab.activeBorderTop': '#ffe600',
      'tab.inactiveBackground': '#0d0d14',
      'tab.inactiveForeground': '#707085',
      'tab.hoverBackground': '#181822',
      'breadcrumb.foreground': '#858599',
      'terminal.background': '#07070a',
      'terminal.foreground': '#f0f0f8',
      'terminalCursor.foreground': '#00f0ff',
      'terminal.ansiGreen': '#00ff88',
      'terminal.ansiCyan': '#00f0ff',
      'terminal.ansiYellow': '#ffe600',
      'interactive.requestBackground': '#0e0e16',
      'textCodeBlock.background': '#050508',
      'textLink.foreground': '#00f0ff',
      'badge.background': '#ffe600',
      'badge.foreground': '#000000',
    },
    tokenColors: [
      { scope: ['keyword', 'keyword.control', 'storage.type'], settings: { foreground: '#ff0055', fontStyle: 'bold' } },
      { scope: ['entity.name.function', 'support.function'], settings: { foreground: '#00f0ff', fontStyle: 'bold' } },
      { scope: ['string', 'string.quoted'], settings: { foreground: '#ffe600' } },
      { scope: ['variable', 'variable.other'], settings: { foreground: '#f0f0f8' } },
      { scope: ['entity.name.type', 'support.type'], settings: { foreground: '#b829ff' } },
      { scope: ['comment'], settings: { foreground: '#4c4c66', fontStyle: 'italic' } },
      { scope: ['constant.numeric', 'constant.language.boolean'], settings: { foreground: '#ff9900' } },
      { scope: ['keyword.operator'], settings: { foreground: '#00f0ff' } },
      { scope: ['entity.name.tag'], settings: { foreground: '#ff0055' } },
    ],
  },

  // 2. Tokyo Night
  {
    id: 'tokyo-night',
    name: '🌃 Tokyo Night',
    description: 'A clean visual theme celebrating the lights of downtown Tokyo at night with soft blues and indigos.',
    type: 'dark',
    accentColor: '#7aa2f7',
    colors: {
      'editor.background': '#1a1b26',
      'editor.foreground': '#a9b1d6',
      'editorLineNumber.foreground': '#363b54',
      'editorLineNumber.activeForeground': '#7aa2f7',
      'editorCursor.foreground': '#c0caf5',
      'editor.selectionBackground': '#283457',
      'editor.lineHighlightBackground': '#1f2335',
      'focusBorder': '#7aa2f7',
      'activityBar.background': '#16161e',
      'activityBar.foreground': '#7aa2f7',
      'activityBar.inactiveForeground': '#414868',
      'activityBarBadge.background': '#7aa2f7',
      'activityBarBadge.foreground': '#15161e',
      'sideBar.background': '#16161e',
      'sideBar.foreground': '#a9b1d6',
      'sideBarTitle.foreground': '#7aa2f7',
      'sideBarSectionHeader.background': '#1f2335',
      'titleBar.activeBackground': '#16161e',
      'titleBar.activeForeground': '#a9b1d6',
      'statusBar.background': '#16161e',
      'statusBar.foreground': '#7aa2f7',
      'statusBar.debuggingBackground': '#f7768e',
      'editorGroupHeader.tabsBackground': '#16161e',
      'tab.activeBackground': '#1a1b26',
      'tab.activeForeground': '#7aa2f7',
      'tab.activeBorderTop': '#7aa2f7',
      'tab.inactiveBackground': '#16161e',
      'tab.inactiveForeground': '#565f89',
      'tab.hoverBackground': '#1f2335',
      'breadcrumb.foreground': '#565f89',
      'terminal.background': '#1a1b26',
      'terminal.foreground': '#a9b1d6',
      'terminalCursor.foreground': '#7aa2f7',
      'terminal.ansiGreen': '#73daca',
      'terminal.ansiCyan': '#7dcfff',
      'terminal.ansiYellow': '#e0af68',
      'interactive.requestBackground': '#1f2335',
      'textCodeBlock.background': '#16161e',
      'textLink.foreground': '#7dcfff',
      'badge.background': '#7aa2f7',
      'badge.foreground': '#15161e',
    },
    tokenColors: [
      { scope: ['keyword', 'keyword.control', 'storage.type'], settings: { foreground: '#bb9af7', fontStyle: 'italic' } },
      { scope: ['entity.name.function', 'support.function'], settings: { foreground: '#7aa2f7' } },
      { scope: ['string', 'string.quoted'], settings: { foreground: '#9ece6a' } },
      { scope: ['variable', 'variable.other'], settings: { foreground: '#c0caf5' } },
      { scope: ['entity.name.type', 'support.type'], settings: { foreground: '#2ac3de' } },
      { scope: ['comment'], settings: { foreground: '#565f89', fontStyle: 'italic' } },
      { scope: ['constant.numeric', 'constant.language.boolean'], settings: { foreground: '#ff9e64' } },
      { scope: ['keyword.operator'], settings: { foreground: '#89ddff' } },
      { scope: ['entity.name.tag'], settings: { foreground: '#f7768e' } },
    ],
  },

  // 3. Dracula Pro
  {
    id: 'dracula-pro',
    name: '🧛 Dracula Pro',
    description: 'Famous dark theme designed for screen comfort with vibrant pink, purple, and pastel green accents.',
    type: 'dark',
    accentColor: '#bd93f9',
    colors: {
      'editor.background': '#282a36',
      'editor.foreground': '#f8f8f2',
      'editorLineNumber.foreground': '#6272a4',
      'editorLineNumber.activeForeground': '#f1fa8c',
      'editorCursor.foreground': '#aeafad',
      'editor.selectionBackground': '#44475a',
      'editor.lineHighlightBackground': '#343746',
      'focusBorder': '#bd93f9',
      'activityBar.background': '#1e1f29',
      'activityBar.foreground': '#f8f8f2',
      'activityBar.inactiveForeground': '#6272a4',
      'activityBarBadge.background': '#ff79c6',
      'activityBarBadge.foreground': '#282a36',
      'sideBar.background': '#21222c',
      'sideBar.foreground': '#f8f8f2',
      'sideBarTitle.foreground': '#bd93f9',
      'sideBarSectionHeader.background': '#282a36',
      'titleBar.activeBackground': '#1e1f29',
      'titleBar.activeForeground': '#f8f8f2',
      'statusBar.background': '#191a21',
      'statusBar.foreground': '#bd93f9',
      'statusBar.debuggingBackground': '#ff5555',
      'editorGroupHeader.tabsBackground': '#1e1f29',
      'tab.activeBackground': '#282a36',
      'tab.activeForeground': '#f8f8f2',
      'tab.activeBorderTop': '#bd93f9',
      'tab.inactiveBackground': '#21222c',
      'tab.inactiveForeground': '#6272a4',
      'tab.hoverBackground': '#343746',
      'breadcrumb.foreground': '#6272a4',
      'terminal.background': '#282a36',
      'terminal.foreground': '#f8f8f2',
      'terminalCursor.foreground': '#bd93f9',
      'terminal.ansiGreen': '#50fa7b',
      'terminal.ansiCyan': '#8be9fd',
      'terminal.ansiYellow': '#f1fa8c',
      'interactive.requestBackground': '#343746',
      'textCodeBlock.background': '#21222c',
      'textLink.foreground': '#8be9fd',
      'badge.background': '#ff79c6',
      'badge.foreground': '#282a36',
    },
    tokenColors: [
      { scope: ['keyword', 'keyword.control', 'storage.type'], settings: { foreground: '#ff79c6' } },
      { scope: ['entity.name.function', 'support.function'], settings: { foreground: '#50fa7b' } },
      { scope: ['string', 'string.quoted'], settings: { foreground: '#f1fa8c' } },
      { scope: ['variable', 'variable.other'], settings: { foreground: '#f8f8f2' } },
      { scope: ['entity.name.type', 'support.type'], settings: { foreground: '#8be9fd', fontStyle: 'italic' } },
      { scope: ['comment'], settings: { foreground: '#6272a4', fontStyle: 'italic' } },
      { scope: ['constant.numeric', 'constant.language.boolean'], settings: { foreground: '#bd93f9' } },
      { scope: ['keyword.operator'], settings: { foreground: '#ff79c6' } },
      { scope: ['entity.name.tag'], settings: { foreground: '#ff79c6' } },
    ],
  },

  // 4. Catppuccin Mocha
  {
    id: 'catppuccin-mocha',
    name: '🐱 Catppuccin Mocha',
    description: 'Soothing warm pastel dark theme with harmonious lavender, sapphire, and peach tones.',
    type: 'dark',
    accentColor: '#cba6f7',
    colors: {
      'editor.background': '#1e1e2e',
      'editor.foreground': '#cdd6f4',
      'editorLineNumber.foreground': '#6c7086',
      'editorLineNumber.activeForeground': '#cba6f7',
      'editorCursor.foreground': '#f5e0dc',
      'editor.selectionBackground': '#585b7066',
      'editor.lineHighlightBackground': '#31324466',
      'focusBorder': '#cba6f7',
      'activityBar.background': '#11111b',
      'activityBar.foreground': '#cba6f7',
      'activityBar.inactiveForeground': '#585b70',
      'activityBarBadge.background': '#cba6f7',
      'activityBarBadge.foreground': '#11111b',
      'sideBar.background': '#181825',
      'sideBar.foreground': '#cdd6f4',
      'sideBarTitle.foreground': '#cba6f7',
      'sideBarSectionHeader.background': '#1e1e2e',
      'titleBar.activeBackground': '#11111b',
      'titleBar.activeForeground': '#cdd6f4',
      'statusBar.background': '#11111b',
      'statusBar.foreground': '#cba6f7',
      'statusBar.debuggingBackground': '#f38ba8',
      'editorGroupHeader.tabsBackground': '#11111b',
      'tab.activeBackground': '#1e1e2e',
      'tab.activeForeground': '#cba6f7',
      'tab.activeBorderTop': '#cba6f7',
      'tab.inactiveBackground': '#181825',
      'tab.inactiveForeground': '#6c7086',
      'tab.hoverBackground': '#313244',
      'breadcrumb.foreground': '#6c7086',
      'terminal.background': '#1e1e2e',
      'terminal.foreground': '#cdd6f4',
      'terminalCursor.foreground': '#cba6f7',
      'terminal.ansiGreen': '#a6e3a1',
      'terminal.ansiCyan': '#89dceb',
      'terminal.ansiYellow': '#f9e2af',
      'interactive.requestBackground': '#313244',
      'textCodeBlock.background': '#181825',
      'textLink.foreground': '#89dceb',
      'badge.background': '#cba6f7',
      'badge.foreground': '#11111b',
    },
    tokenColors: [
      { scope: ['keyword', 'keyword.control', 'storage.type'], settings: { foreground: '#cba6f7', fontStyle: 'bold' } },
      { scope: ['entity.name.function', 'support.function'], settings: { foreground: '#89b4fa' } },
      { scope: ['string', 'string.quoted'], settings: { foreground: '#a6e3a1' } },
      { scope: ['variable', 'variable.other'], settings: { foreground: '#cdd6f4' } },
      { scope: ['entity.name.type', 'support.type'], settings: { foreground: '#f9e2af' } },
      { scope: ['comment'], settings: { foreground: '#6c7086', fontStyle: 'italic' } },
      { scope: ['constant.numeric', 'constant.language.boolean'], settings: { foreground: '#fab387' } },
      { scope: ['keyword.operator'], settings: { foreground: '#94e2d5' } },
      { scope: ['entity.name.tag'], settings: { foreground: '#f38ba8' } },
    ],
  },

  // 5. Nord Frost
  {
    id: 'nord-frost',
    name: '❄️ Nord Frost',
    description: 'An arctic, north-bluish clean color palette crafted for elegant visual coherence.',
    type: 'dark',
    accentColor: '#88c0d0',
    colors: {
      'editor.background': '#2e3440',
      'editor.foreground': '#d8dee9',
      'editorLineNumber.foreground': '#4c566a',
      'editorLineNumber.activeForeground': '#88c0d0',
      'editorCursor.foreground': '#d8dee9',
      'editor.selectionBackground': '#434c5ecc',
      'editor.lineHighlightBackground': '#3b4252',
      'focusBorder': '#88c0d0',
      'activityBar.background': '#242933',
      'activityBar.foreground': '#88c0d0',
      'activityBar.inactiveForeground': '#4c566a',
      'activityBarBadge.background': '#88c0d0',
      'activityBarBadge.foreground': '#2e3440',
      'sideBar.background': '#272c36',
      'sideBar.foreground': '#d8dee9',
      'sideBarTitle.foreground': '#88c0d0',
      'sideBarSectionHeader.background': '#2e3440',
      'titleBar.activeBackground': '#242933',
      'titleBar.activeForeground': '#d8dee9',
      'statusBar.background': '#242933',
      'statusBar.foreground': '#88c0d0',
      'statusBar.debuggingBackground': '#bf616a',
      'editorGroupHeader.tabsBackground': '#242933',
      'tab.activeBackground': '#2e3440',
      'tab.activeForeground': '#88c0d0',
      'tab.activeBorderTop': '#88c0d0',
      'tab.inactiveBackground': '#272c36',
      'tab.inactiveForeground': '#4c566a',
      'tab.hoverBackground': '#3b4252',
      'breadcrumb.foreground': '#4c566a',
      'terminal.background': '#2e3440',
      'terminal.foreground': '#d8dee9',
      'terminalCursor.foreground': '#88c0d0',
      'terminal.ansiGreen': '#a3be8c',
      'terminal.ansiCyan': '#88c0d0',
      'terminal.ansiYellow': '#ebcb8b',
      'interactive.requestBackground': '#3b4252',
      'textCodeBlock.background': '#272c36',
      'textLink.foreground': '#88c0d0',
      'badge.background': '#88c0d0',
      'badge.foreground': '#2e3440',
    },
    tokenColors: [
      { scope: ['keyword', 'keyword.control', 'storage.type'], settings: { foreground: '#81a1c1' } },
      { scope: ['entity.name.function', 'support.function'], settings: { foreground: '#88c0d0' } },
      { scope: ['string', 'string.quoted'], settings: { foreground: '#a3be8c' } },
      { scope: ['variable', 'variable.other'], settings: { foreground: '#d8dee9' } },
      { scope: ['entity.name.type', 'support.type'], settings: { foreground: '#8fbcbb' } },
      { scope: ['comment'], settings: { foreground: '#4c566a', fontStyle: 'italic' } },
      { scope: ['constant.numeric', 'constant.language.boolean'], settings: { foreground: '#b48ead' } },
      { scope: ['keyword.operator'], settings: { foreground: '#81a1c1' } },
      { scope: ['entity.name.tag'], settings: { foreground: '#81a1c1' } },
    ],
  },

  // 6. OLED Pure Black
  {
    id: 'oled-pure-black',
    name: '🌑 OLED Pure Black',
    description: 'True #000000 deep black backgrounds for maximum contrast, battery savings and crisp readability.',
    type: 'dark',
    accentColor: '#00ff88',
    colors: {
      'editor.background': '#000000',
      'editor.foreground': '#ffffff',
      'editorLineNumber.foreground': '#333333',
      'editorLineNumber.activeForeground': '#00ff88',
      'editorCursor.foreground': '#00ff88',
      'editor.selectionBackground': '#222222',
      'editor.lineHighlightBackground': '#111111',
      'focusBorder': '#00ff88',
      'activityBar.background': '#000000',
      'activityBar.foreground': '#00ff88',
      'activityBar.inactiveForeground': '#444444',
      'activityBarBadge.background': '#00ff88',
      'activityBarBadge.foreground': '#000000',
      'sideBar.background': '#050505',
      'sideBar.foreground': '#dddddd',
      'sideBarTitle.foreground': '#00ff88',
      'sideBarSectionHeader.background': '#0c0c0c',
      'titleBar.activeBackground': '#000000',
      'titleBar.activeForeground': '#ffffff',
      'statusBar.background': '#000000',
      'statusBar.foreground': '#00ff88',
      'statusBar.debuggingBackground': '#ff3366',
      'editorGroupHeader.tabsBackground': '#050505',
      'tab.activeBackground': '#000000',
      'tab.activeForeground': '#00ff88',
      'tab.activeBorderTop': '#00ff88',
      'tab.inactiveBackground': '#080808',
      'tab.inactiveForeground': '#555555',
      'tab.hoverBackground': '#151515',
      'breadcrumb.foreground': '#666666',
      'terminal.background': '#000000',
      'terminal.foreground': '#ffffff',
      'terminalCursor.foreground': '#00ff88',
      'terminal.ansiGreen': '#00ff88',
      'terminal.ansiCyan': '#00f0ff',
      'terminal.ansiYellow': '#ffff00',
      'interactive.requestBackground': '#111111',
      'textCodeBlock.background': '#080808',
      'textLink.foreground': '#00f0ff',
      'badge.background': '#00ff88',
      'badge.foreground': '#000000',
    },
    tokenColors: [
      { scope: ['keyword', 'keyword.control', 'storage.type'], settings: { foreground: '#ff3366', fontStyle: 'bold' } },
      { scope: ['entity.name.function', 'support.function'], settings: { foreground: '#00ff88', fontStyle: 'bold' } },
      { scope: ['string', 'string.quoted'], settings: { foreground: '#ffe600' } },
      { scope: ['variable', 'variable.other'], settings: { foreground: '#ffffff' } },
      { scope: ['entity.name.type', 'support.type'], settings: { foreground: '#00f0ff' } },
      { scope: ['comment'], settings: { foreground: '#555555', fontStyle: 'italic' } },
      { scope: ['constant.numeric', 'constant.language.boolean'], settings: { foreground: '#ff9900' } },
      { scope: ['keyword.operator'], settings: { foreground: '#00f0ff' } },
      { scope: ['entity.name.tag'], settings: { foreground: '#ff3366' } },
    ],
  },

  // 7. Clean Minimalist Light
  {
    id: 'clean-light',
    name: '☀️ Clean Minimalist Light',
    description: 'Crisp, modern, high-clarity daytime light theme with soft slate backgrounds and indigo accents.',
    type: 'light',
    accentColor: '#4f46e5',
    colors: {
      'editor.background': '#ffffff',
      'editor.foreground': '#1e293b',
      'editorLineNumber.foreground': '#94a3b8',
      'editorLineNumber.activeForeground': '#4f46e5',
      'editorCursor.foreground': '#4f46e5',
      'editor.selectionBackground': '#e0e7ff',
      'editor.lineHighlightBackground': '#f8fafc',
      'focusBorder': '#4f46e5',
      'activityBar.background': '#f1f5f9',
      'activityBar.foreground': '#4f46e5',
      'activityBar.inactiveForeground': '#64748b',
      'activityBarBadge.background': '#4f46e5',
      'activityBarBadge.foreground': '#ffffff',
      'sideBar.background': '#f8fafc',
      'sideBar.foreground': '#334155',
      'sideBarTitle.foreground': '#0f172a',
      'sideBarSectionHeader.background': '#e2e8f0',
      'titleBar.activeBackground': '#f1f5f9',
      'titleBar.activeForeground': '#0f172a',
      'statusBar.background': '#4f46e5',
      'statusBar.foreground': '#ffffff',
      'statusBar.debuggingBackground': '#e11d48',
      'editorGroupHeader.tabsBackground': '#f1f5f9',
      'tab.activeBackground': '#ffffff',
      'tab.activeForeground': '#4f46e5',
      'tab.activeBorderTop': '#4f46e5',
      'tab.inactiveBackground': '#f8fafc',
      'tab.inactiveForeground': '#64748b',
      'tab.hoverBackground': '#e2e8f0',
      'breadcrumb.foreground': '#64748b',
      'terminal.background': '#ffffff',
      'terminal.foreground': '#1e293b',
      'terminalCursor.foreground': '#4f46e5',
      'terminal.ansiGreen': '#059669',
      'terminal.ansiCyan': '#0284c7',
      'terminal.ansiYellow': '#d97706',
      'interactive.requestBackground': '#f1f5f9',
      'textCodeBlock.background': '#f8fafc',
      'textLink.foreground': '#4f46e5',
      'badge.background': '#4f46e5',
      'badge.foreground': '#ffffff',
    },
    tokenColors: [
      { scope: ['keyword', 'keyword.control', 'storage.type'], settings: { foreground: '#7c3aed', fontStyle: 'bold' } },
      { scope: ['entity.name.function', 'support.function'], settings: { foreground: '#2563eb' } },
      { scope: ['string', 'string.quoted'], settings: { foreground: '#059669' } },
      { scope: ['variable', 'variable.other'], settings: { foreground: '#0f172a' } },
      { scope: ['entity.name.type', 'support.type'], settings: { foreground: '#0284c7' } },
      { scope: ['comment'], settings: { foreground: '#94a3b8', fontStyle: 'italic' } },
      { scope: ['constant.numeric', 'constant.language.boolean'], settings: { foreground: '#ea580c' } },
      { scope: ['keyword.operator'], settings: { foreground: '#475569' } },
      { scope: ['entity.name.tag'], settings: { foreground: '#e11d48' } },
    ],
  },
];
