import * as vscode from 'vscode';
import * as path from 'path';
import * as fs from 'fs';
import { TokenRule } from './types';

export class ThemeExporter {
  public static generateThemeJson(
    themeName: string,
    type: 'dark' | 'light',
    colors: Record<string, string>,
    tokenColors: TokenRule[]
  ): string {
    const themeDef = {
      name: themeName,
      type: type,
      colors: colors,
      tokenColors: tokenColors.map((r) => ({
        name: Array.isArray(r.scope) ? r.scope.join(', ') : r.scope,
        scope: r.scope,
        settings: r.settings,
      })),
    };
    return JSON.stringify(themeDef, null, 2);
  }

  public static async exportToFolder(
    targetDir: string,
    themeName: string,
    type: 'dark' | 'light',
    colors: Record<string, string>,
    tokenColors: TokenRule[]
  ): Promise<string> {
    const slug = themeName.toLowerCase().replace(/[^a-z0-9]/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '');
    const extensionDir = path.join(targetDir, slug + '-theme');
    const themesDir = path.join(extensionDir, 'themes');

    if (!fs.existsSync(themesDir)) {
      fs.mkdirSync(themesDir, { recursive: true });
    }

    const themeJsonFilename = `${slug}-color-theme.json`;
    const themeJsonPath = path.join(themesDir, themeJsonFilename);
    const themeContent = this.generateThemeJson(themeName, type, colors, tokenColors);
    fs.writeFileSync(themeJsonPath, themeContent, 'utf-8');

    const pkgJson = {
      name: slug + '-theme',
      displayName: themeName,
      description: `Custom VS Code theme generated by SimpleSignal Theme Studio`,
      version: '1.0.0',
      publisher: 'custom',
      engines: {
        vscode: '^1.80.0',
      },
      categories: ['Themes'],
      contributes: {
        themes: [
          {
            label: themeName,
            uiTheme: type === 'light' ? 'vs' : 'vs-dark',
            path: `./themes/${themeJsonFilename}`,
          },
        ],
      },
    };

    fs.writeFileSync(path.join(extensionDir, 'package.json'), JSON.stringify(pkgJson, null, 2), 'utf-8');
    fs.writeFileSync(
      path.join(extensionDir, 'README.md'),
      `# ${themeName}\n\nA custom theme generated with [SimpleSignal Theme Studio](https://github.com/falabellamichael/SimpleSignal-VS-Code-Extension).\n`,
      'utf-8'
    );

    return extensionDir;
  }
}
